version: "3.8"

services:
  api-server:
    build:
      context: ./api-server
      dockerfile: dockerfile
    volumes:
      - ./api-server:/usr/src/app
    ports:
      - "5000:5000"
    env_file:
      - database.env 
    depends_on: 
      - database
    links:
      - database

  api-client:
    environment:
      CHOKIDAR_USEPOLLING: "true"
    build:
      context: ./api-client
      dockerfile: dockerfile
    volumes:
      - ./api-client/:/usr/src/app
    ports:
      - "8080:8080"

  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - 5432:5432
      

volumes:
  database-data: # named volumes can be managed easier using docker-compose
