version: "3.8"

services:
  api-server:
    build:
      context: ./api-server
      dockerfile: dockerfile
    volumes:
      - ./api-server:/usr/src/app
    ports:
      - "5000:5000"

  api-client:
    build:
      context: ./api-client
      dockerfile: dockerfile
    volumes:
      - ./api-client/:/usr/src/app
    ports:
      - "3000:3000"
